### ISSUE TITLE
replace gulp-livereload to gulp-webserver

### ISSUE THREAD

**Issue by chuanxd** [g0v/cuora#3]
can I replace gulp-livereload to gulp-webserver ?

gulp-webserver can automatically open browser

**Comment by jessy1092** [comment]
@chuanxd Welcome!!  Just do it. :)

**Comment by chuanxd** [comment]
@jessy1092 can u help me merge https://github.com/g0v/cuora/pull/4

**Comment by jessy1092** [comment]
@chuanxd sorry, I forgot it.  orz
